# Changes here will be overwritten by Copier
_commit: 4a2fff5
_src_path: git@github.com:cagov/caldata-infrastructure-template.git
dbt_profile_name: dse_snowflake
dbt_target: Snowflake
email_address: aeri.shan@innovation.ca.gov
friendly_project_name: User Journey Tracking
license: MIT
project_name: caldata-user-journey-tracking
team_name: DSE
