# Changes here will be overwritten by Copier
_commit: cdb1adc
_src_path: git@github.com:cagov/caldata-infrastructure-template.git
dbt_profile_name: dse_snowflake
email_address: britt.allen@innovation.ca.gov
friendly_project_name: Web Analytics
license: MIT
project_name: caldata-web-analytics
team_name: DSE
