# Project settings
name: dse_snowflake
version: "1.0.0"
config-version: 2

flags:
  send_anonymous_usage_stats: false
  use_colors: true
  warn_error: true

# This setting configures which "profile" dbt uses for this project.
profile: dse_snowflake

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - target
  - dbt_packages

vars:
  # The date when the benefits recommender widget was put into production
  # (this excludes the pilot program)
  br_widget_start_date: "'2023-11-16'"
  # First date of the GA4 BigQuery dataset
  ga_data_start_date: "'2022-10-31'"

models:
  dse_snowflake:
    +begin: "{{ '2022-10-31' if target.name == 'prd' else ((modules.datetime.datetime.now() - modules.datetime.timedelta(2)) - modules.datetime.timedelta(7)).isoformat() }}"
    +batch_size: day
    staging:
      +materialized: view
      google_analytics:
        +schema: google_analytics
      geo:
        +schema: geo
    intermediate:
      +materialized: view
      geo:
        +schema: geo
      benefits_recommender:
        +schema: benefits_recommender
      google_analytics:
        +schema: google_analytics
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_ANALYTICS_DB', 'ANALYTICS_DEV') }}"
      benefits_recommender:
        +schema: benefits_recommender
      engaged_ca:
        +schema: engaged_ca
