# Project settings
name: dse_snowflake
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: dse_snowflake

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - target
  - dbt_packages

vars:
  # The date when the benefits recommender widget was put into production
  # (this excludes the pilot program)
  br_widget_start_date: "'2023-11-16'"
  # Date requested by Regan
  ga_data_start_date: "'2023-08-16'"

models:
  dse_snowflake:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
      engaged_ca:
        +schema: engaged_ca
      benefits_recommender:
        +schema: benefits_recommender
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_ANALYTICS_DB', 'ANALYTICS_DEV') }}"
      benefits_recommender:
        +schema: benefits_recommender
