name: nightly
on:
  # Run nightly at 9AM UTC (1AM Pacific)
  schedule:
    - cron: "7 9 * * *"
  # Also run on push to main
  push:
    branches:
      - main
  # Also allow for manual triggers
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: transform/ci
  DBT_ANALYTICS_DB: ANALYTICS_PRD
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_PRD }}
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_PRD }}
  SNOWFLAKE_ROLE: TRANSFORMER_PRD
  SNOWFLAKE_WAREHOUSE: TRANSFORMING_XL_PRD
  SNOWFLAKE_DATABASE: TRANSFORM_PRD
  SNOWFLAKE_SCHEMA: BR

jobs:
  build-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies
        run: poetry install --no-root
      - name: Build dbt project
        run: |
          poetry run dbt deps --project-dir transform
          poetry run dbt build --project-dir transform --target prd
