name: nightly
on:
  # Run nightly at 9AM UTC (1AM Pacific)
  schedule:
    - cron: "7 9 * * *"
  # Also run on push to main
  push:
    branches:
      - main
  # Also allow for manual triggers
  workflow_dispatch:

env:
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_PRD }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_PRD }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install
      - name: Build dbt project
        env:
          DBT_PROFILES_DIR: transform/ci
          DBT_ANALYTICS_DB: ANALYTICS_PRD
          DBT_RAW_DB: RAW_ENGCA_PRD
          SNOWFLAKE_ROLE: TRANSFORMER_PRD
          SNOWFLAKE_DATABASE: TRANSFORM_PRD
          SNOWFLAKE_WAREHOUSE: TRANSFORMING_XL_PRD
        run: |
          poetry run dbt deps --project-dir transform --target prd
          poetry run dbt build --project-dir transform --target prd
