name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  DBT_PROFILES_DIR: ci

  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_DEV }}
  SNOWFLAKE_ROLE: READER_DEV
  SNOWFLAKE_WAREHOUSE: REPORTING_XS_DEV
  SNOWFLAKE_DATABASE: ANALYTICS_DEV
  SNOWFLAKE_SCHEMA: ci_should_not_create_this_schema

defaults:
  run:
    shell: bash -l {0}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install dependencies
        run: |
          poetry install
      - uses: pre-commit/action@v3.0.0
