name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  DBT_PROFILES_DIR: transform/ci

  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_DEV }}
  SNOWFLAKE_ROLE: READER_DEV
  SNOWFLAKE_WAREHOUSE: REPORTING_XS_DEV
  SNOWFLAKE_DATABASE: ANALYTICS_DEV
  SNOWFLAKE_SCHEMA: ci_should_not_create_this_schema

defaults:
  run:
    shell: bash -l {0}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-path: .venv
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Install dbt deps
        run: poetry run dbt deps --project-dir transform
      - uses: pre-commit/action@v3.0.0
